### ISSUE TITLE
it´s not possible to send raw hex codes

### ISSUE THREAD

**Issue by arichterras** [bitfocus/companion-module-generic-tcp-serial#1]
If raw hex codes are sent to the tcp-serial instance from another tcp instance, for example the "generic tcp and udp requests instance", the data is misinterpreted. Why is `socket.setEncoding('latin1');` used in line 237? Is this Encoding necassary on TCP Server receive side? Should it not be only on the TCP Client send side? Removing line 237 fixes the issue.

**Comment by istnv** [comment]
`latin1` encoding is unfiltered ASCII. By default, internal strings are UTF-8 and will wrap any binary bytes over x7F which corrupts the binary data.

**Comment by istnv** [comment]
The module is bi-directional and sends any response from the serial device back to the TCP client. When I put the module together, sending binary would not work without `latin1`.

**Comment by arichterras** [comment]
in my understanding only the data reveived from the tcp client and send to the serial device is encoded in latin1. The data send from the serial device to the tcp client is not encoded and that works fine. Are java script string not utf16 by default? Bytes above x7F should be no problem.

**Comment by istnv** [comment]
Any UTF encoding I tried added extra characters for bytes over x7F. Some of those upper bytes are used as extension characters in UTF-16, so they also get 'escaped' in the data stream. `latin1` was the only one I found that leaves the stream untouched.

**Comment by arichterras** [comment]
This is exactly what the latin1 encoding does on my setup. I send x81x01x04x07x24xFF to the tcp-Serial module the output of the usb to serial adapter is xC2x81x01x04x07x24xC3xBF. If the line 237 `socket.setEncoding('latin1');` is removed the result is x81x01x04x07x24xFF. If i´m using an hardware tcp to serial converter the result is also correct. Can you explain me why the encoding ist necassary and only in one direction?

**Comment by istnv** [comment]
The encoding **should** be both directions and it is intended to tell javascript to _leave it alone._ Somewhere in the chain, bytes are being re-encoded to UTF-16. (UTF8 and UTF16 both encode bytes over x7F the same)

The `generic-tcp-udp module` would alter the hex codes if `latin1` wasn't used. So it was also added to the `tcp-serial` module.

Looking over the docs for the net.socket again, that encoding step is not needed there since it will transmit the `buffer` unchanged. Setting the incoming encoding tells the socket to convert from `latin1` to a UTF-16 string.

I will submit an update soon. Thanks for your comments.

**Comment by istnv** [comment]
@arichterras Can we close this?

**Comment by arichterras** [comment]
Yes it´s fixed. Thanks!
